### ISSUE TITLE
Grass disappearing after changing the instance count

### ISSUE THREAD

**Issue by rashnux** [Malidos/Grass-Shader-Example#1]
### Godot Version

v4.2.2 and v4.3.beta3.official

### System information
MacBook with M1 Pro Chip

### Issue description

Grass disappears after changing the instance count in `GrassInstance3D`, which is a `MultiMeshInstance3D`. It might be related to this problem:

https://github.com/godotengine/godot/issues/75485

**Comment by Malidos** [comment]
It has nothing to do with the shader itself but rather Godot's MultiMeshInstance. I suggest you just try not to change the instance count at runtime.
